// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.0
// source: search2.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SearchRequest2_Corpus int32

const (
	SearchRequest2_UNIVERSAL SearchRequest2_Corpus = 0
	SearchRequest2_WEB       SearchRequest2_Corpus = 1
	SearchRequest2_IMAGES    SearchRequest2_Corpus = 2
	SearchRequest2_LOCAL     SearchRequest2_Corpus = 3
	SearchRequest2_NEWS      SearchRequest2_Corpus = 4
	SearchRequest2_PRODUCTS  SearchRequest2_Corpus = 5
	SearchRequest2_VIDEO     SearchRequest2_Corpus = 6
)

// Enum value maps for SearchRequest2_Corpus.
var (
	SearchRequest2_Corpus_name = map[int32]string{
		0: "UNIVERSAL",
		1: "WEB",
		2: "IMAGES",
		3: "LOCAL",
		4: "NEWS",
		5: "PRODUCTS",
		6: "VIDEO",
	}
	SearchRequest2_Corpus_value = map[string]int32{
		"UNIVERSAL": 0,
		"WEB":       1,
		"IMAGES":    2,
		"LOCAL":     3,
		"NEWS":      4,
		"PRODUCTS":  5,
		"VIDEO":     6,
	}
)

func (x SearchRequest2_Corpus) Enum() *SearchRequest2_Corpus {
	p := new(SearchRequest2_Corpus)
	*p = x
	return p
}

func (x SearchRequest2_Corpus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchRequest2_Corpus) Descriptor() protoreflect.EnumDescriptor {
	return file_search2_proto_enumTypes[0].Descriptor()
}

func (SearchRequest2_Corpus) Type() protoreflect.EnumType {
	return &file_search2_proto_enumTypes[0]
}

func (x SearchRequest2_Corpus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SearchRequest2_Corpus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SearchRequest2_Corpus(num)
	return nil
}

// Deprecated: Use SearchRequest2_Corpus.Descriptor instead.
func (SearchRequest2_Corpus) EnumDescriptor() ([]byte, []int) {
	return file_search2_proto_rawDescGZIP(), []int{0, 0}
}

type SearchRequest2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query         *string                `protobuf:"bytes,1,req,name=query" json:"query,omitempty"`
	PageNumber    *int32                 `protobuf:"varint,2,opt,name=page_number,json=pageNumber" json:"page_number,omitempty"`
	ResultPerPage *int32                 `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,def=10" json:"result_per_page,omitempty"`
	Corpus        *SearchRequest2_Corpus `protobuf:"varint,4,opt,name=corpus,enum=SearchRequest2_Corpus,def=0" json:"corpus,omitempty"`
}

// Default values for SearchRequest2 fields.
const (
	Default_SearchRequest2_ResultPerPage = int32(10)
	Default_SearchRequest2_Corpus        = SearchRequest2_UNIVERSAL
)

func (x *SearchRequest2) Reset() {
	*x = SearchRequest2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRequest2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest2) ProtoMessage() {}

func (x *SearchRequest2) ProtoReflect() protoreflect.Message {
	mi := &file_search2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest2.ProtoReflect.Descriptor instead.
func (*SearchRequest2) Descriptor() ([]byte, []int) {
	return file_search2_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest2) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

func (x *SearchRequest2) GetPageNumber() int32 {
	if x != nil && x.PageNumber != nil {
		return *x.PageNumber
	}
	return 0
}

func (x *SearchRequest2) GetResultPerPage() int32 {
	if x != nil && x.ResultPerPage != nil {
		return *x.ResultPerPage
	}
	return Default_SearchRequest2_ResultPerPage
}

func (x *SearchRequest2) GetCorpus() SearchRequest2_Corpus {
	if x != nil && x.Corpus != nil {
		return *x.Corpus
	}
	return Default_SearchRequest2_Corpus
}

type SearchResponse2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bundles []*Bundle `protobuf:"bytes,1,rep,name=bundles" json:"bundles,omitempty"` // slice
}

func (x *SearchResponse2) Reset() {
	*x = SearchResponse2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponse2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse2) ProtoMessage() {}

func (x *SearchResponse2) ProtoReflect() protoreflect.Message {
	mi := &file_search2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse2.ProtoReflect.Descriptor instead.
func (*SearchResponse2) Descriptor() ([]byte, []int) {
	return file_search2_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse2) GetBundles() []*Bundle {
	if x != nil {
		return x.Bundles
	}
	return nil
}

var File_search2_proto protoreflect.FileDescriptor

var file_search2_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0c, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x02,
	0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32,
	0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x67,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x3a, 0x02, 0x31, 0x30, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x65, 0x72, 0x50,
	0x61, 0x67, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x63, 0x6f, 0x72, 0x70, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x32, 0x2e, 0x43, 0x6f, 0x72, 0x70, 0x75, 0x73, 0x3a, 0x09, 0x55, 0x4e, 0x49,
	0x56, 0x45, 0x52, 0x53, 0x41, 0x4c, 0x52, 0x06, 0x63, 0x6f, 0x72, 0x70, 0x75, 0x73, 0x22, 0x5a,
	0x0a, 0x06, 0x43, 0x6f, 0x72, 0x70, 0x75, 0x73, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x49, 0x56,
	0x45, 0x52, 0x53, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x57, 0x45, 0x42, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x53, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05,
	0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x45, 0x57, 0x53, 0x10,
	0x04, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x52, 0x4f, 0x44, 0x55, 0x43, 0x54, 0x53, 0x10, 0x05, 0x12,
	0x09, 0x0a, 0x05, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x06, 0x22, 0x34, 0x0a, 0x0f, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x12, 0x21, 0x0a,
	0x07, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07,
	0x2e, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x07, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73,
	0x32, 0x3f, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x32, 0x12, 0x2d, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x0f, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0x1a, 0x10, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x22,
	0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_search2_proto_rawDescOnce sync.Once
	file_search2_proto_rawDescData = file_search2_proto_rawDesc
)

func file_search2_proto_rawDescGZIP() []byte {
	file_search2_proto_rawDescOnce.Do(func() {
		file_search2_proto_rawDescData = protoimpl.X.CompressGZIP(file_search2_proto_rawDescData)
	})
	return file_search2_proto_rawDescData
}

var file_search2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_search2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_search2_proto_goTypes = []interface{}{
	(SearchRequest2_Corpus)(0), // 0: SearchRequest2.Corpus
	(*SearchRequest2)(nil),     // 1: SearchRequest2
	(*SearchResponse2)(nil),    // 2: SearchResponse2
	(*Bundle)(nil),             // 3: Bundle
}
var file_search2_proto_depIdxs = []int32{
	0, // 0: SearchRequest2.corpus:type_name -> SearchRequest2.Corpus
	3, // 1: SearchResponse2.bundles:type_name -> Bundle
	1, // 2: SearchService2.Search:input_type -> SearchRequest2
	2, // 3: SearchService2.Search:output_type -> SearchResponse2
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_search2_proto_init() }
func file_search2_proto_init() {
	if File_search2_proto != nil {
		return
	}
	file_search_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_search2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRequest2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_search2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResponse2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_search2_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search2_proto_goTypes,
		DependencyIndexes: file_search2_proto_depIdxs,
		EnumInfos:         file_search2_proto_enumTypes,
		MessageInfos:      file_search2_proto_msgTypes,
	}.Build()
	File_search2_proto = out.File
	file_search2_proto_rawDesc = nil
	file_search2_proto_goTypes = nil
	file_search2_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SearchService2Client is the client API for SearchService2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchService2Client interface {
	Search(ctx context.Context, in *SearchRequest2, opts ...grpc.CallOption) (*SearchResponse2, error)
}

type searchService2Client struct {
	cc grpc.ClientConnInterface
}

func NewSearchService2Client(cc grpc.ClientConnInterface) SearchService2Client {
	return &searchService2Client{cc}
}

func (c *searchService2Client) Search(ctx context.Context, in *SearchRequest2, opts ...grpc.CallOption) (*SearchResponse2, error) {
	out := new(SearchResponse2)
	err := c.cc.Invoke(ctx, "/SearchService2/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchService2Server is the server API for SearchService2 service.
type SearchService2Server interface {
	Search(context.Context, *SearchRequest2) (*SearchResponse2, error)
}

// UnimplementedSearchService2Server can be embedded to have forward compatible implementations.
type UnimplementedSearchService2Server struct {
}

func (*UnimplementedSearchService2Server) Search(context.Context, *SearchRequest2) (*SearchResponse2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}

func RegisterSearchService2Server(s *grpc.Server, srv SearchService2Server) {
	s.RegisterService(&_SearchService2_serviceDesc, srv)
}

func _SearchService2_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchService2Server).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SearchService2/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchService2Server).Search(ctx, req.(*SearchRequest2))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchService2_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SearchService2",
	HandlerType: (*SearchService2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchService2_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search2.proto",
}
